### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by Doc-Han** [AmosAidoo/spotlight-on-the-word#1]
Please, you need a project roadmap with future features so that I'll know how to contribute to this project.

**Comment by Doc-Han** [comment]
Again it should contain start scripts for us to be able to bootstrap the project after cloning.
Check this example from my project [here](https://github.com/Doc-Han/T-Shirt-Editor)
Read the readme

**Comment by AmosAidoo** [comment]
It will be ready soon. Thanks
